sonar.projectKey=nestjs-keycloak
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info
